### ISSUE TITLE
Not building in osx

### ISSUE THREAD

**Issue by niklaspollonen** [juhakivekas/explision#1]
Got an error on OSX during build: 

src/struct/shape.c:2:10: fatal error: 'malloc.h' file not found
#include <malloc.h>

**Fixed** it by replacing **#include <malloc.h>** with **#include <stdlib.h>**

**Comment by juhakivekas** [comment]
I've only ever built this on Ubuntu/Debian. If you make other modifications to get the code compiling, then please make a PR so I can incorporate them into the codebase. Even just a copy-paste of `git diff` as a comment if enough if you're not used to making PRs :)

**Comment by juhakivekas** [comment]
I did the edits and compiled the code on my osx machine and it seems to work well now so I pushed the changes. I also took the chance to delete some dead code in case you'll be looking at this more closely :)
